[versions]
kotlin = "1.8.22"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij = "org.jetbrains.intellij:1.17.3"
spotless = "com.diffplug.spotless:5.10.2"

[libraries]
kotlin-compilerEmbeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

googlejavaformat = "com.google.googlejavaformat:google-java-format:1.22.0"
guava = "com.google.guava:guava:32.0.0-jre"
truth = "com.google.truth:truth:1.0"
junit = "junit:junit:4.13.1"
jna = "net.java.dev.jna:jna:4.2.2"
