/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.com.google.guava.guava)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib.jdk7)
    api(libs.org.jetbrains.kotlin.kotlin.test)
    api(libs.org.jetbrains.kotlin.kotlin.compiler.embeddable)
    api(libs.net.java.dev.jna.jna)
    api(libs.com.google.googlejavaformat.google.java.format)
    testImplementation(libs.junit.junit)
    testImplementation(libs.com.google.truth.truth)
}

description = "Ktfmt"
