name: Build and Test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against relevant LTS versions of Java
        java: [ 17, 21 ]
    name: Build ktfmt on Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: zulu
    - name: Build ktfmt_idea_plugin
      run: ./gradlew :idea_plugin:build --stacktrace --no-daemon
    - name: Build the Online Formatter
      run: ./gradlew :lambda:build --stacktrace --no-daemon
    - name: Build ktfmt
      run: ./gradlew :ktfmt:build --stacktrace --no-daemon
